remote_theme: kyleplo/blank-theme

title: Blank Theme Sample
author: kyleplo
description: Example site with the Blank theme.
# Link to a profile picture - required
avatar: https://avatars1.githubusercontent.com/u/31634240?v=4&s=40
# path to your repository - required
repo: kyleplo/blank-theme
# social links - optional
mail:  
twitter_username: 
github_username: kyleplo
# theme - fill out if you want to change colors

theme_nav: "#dddddd" # color of the navbar
theme_accent: "#1199ff" # color of links and some other things
theme_tags: "#ee7700" # color of tags on post pages
theme_footer: "#999999" # color of the footer
