remote_theme: kyleplo/blank-theme

title: Blank Theme Sample
author: kyleplo
description: Example site with the Blank theme.
# Link to a profile picture - required
avatar: https://avatars0.githubusercontent.com/u/43795230?s=400&v=4
# path to your repository - required
repo: kyleplo/blank-theme
# social links - optional
mail:  
twitter_username: 
github_username: kyleplo
# theme - fill out if you want to change colors

theme_nav: "#dddddd" # color of the navbar
theme_accent: "#1199ff" # color of links and some other things
theme_tags: "#ee7700" # color of tags on post pages
theme_footer: "#999999" # color of the footer

# Optional config - just for more customization or troubleshooting
# how many posts to show per page
paginate: 15

# change this if you are on a project repo, not a username.github.io repo
# for example, if your repo is hello-world, set this to hello-world
path: 

# Ignore the rest of this file unless you want to change more settings
rss: rss
permalink: /blog/:title/

paginate_path: "/blog/:num/"

sass:
    style: compact

plugins:
 - jekyll-feed
